In [1]:
import numpy as np

## Question 1: valid Sudoku

In [2]:
s=np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
    
])
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [9]:
valid=True
b=np.sum(s,axis=1)

for i in b:
    if i !=45:
        valid=False

In [10]:
c=np.sum(s,axis=0)
for i in c:
    if i !=45:
        valid=False

In [17]:
b1=s[0:3,0:3].sum()
b2=s[0:3,3:6].sum()
b3=s[0:3,6:9].sum()
b4=s[3:6,0:3].sum()
b5=s[3:6,3:6].sum()
b6=s[3:6,6:9].sum()
b7=s[6:9,0:3].sum()
b8=s[6:9,3:6].sum()
b9=s[6:9,6:9].sum()

In [18]:
if b1==b2==b3==b4==b5==b6==b7==b8==b9==45:
    print(45)

45


## Question 2 : General Questions

In [63]:
# columns: [Age,Math Marks, Science marks]
data=np.array([
    [18,85,78], # Student 1
    [19,92,88], # Student 2
    [17,76,95], # Student 3
    [18,65,70], # Student 4
    [20,90,85]  # Student 5
])

In [21]:
#Get the shape of matrix
data.shape

(5, 3)

In [26]:
# Find the Average age of Students
average_age=data[:,0].sum()/5
average_age

np.float64(18.4)

In [27]:
# Extract Math marks of all students
math_mark=data[:,1]
math_mark

array([85, 92, 76, 65, 90])

In [28]:
# Find the highest Science mark
data[:,2].max()

np.int64(95)

In [37]:
# Get details of the student who scored more than 90 in math.
destails=data[:,1]>90
data[destails]

array([[19, 92, 88]])

In [30]:
# Increase math marks of all students by 5
data[:,1]+5

array([90, 97, 81, 70, 95])

In [40]:
# Find how many students are younger than 19
youngerstudent=data[:,0]<19
len(data[youngerstudent])

3

In [49]:
# Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [51]:
# Get data of student who scored at least 80 in both subjects
details=((data[:,1]>=80) & (data[:,2]>=80))

In [52]:
details

array([False,  True, False, False,  True])

In [53]:
data[details]

array([[19, 92, 88],
       [20, 90, 85]])

In [64]:
# replace all science marks <75 with 0
data


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [65]:
data[:,2][data[:,2]<75]=0

In [66]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])