In [1]:
import numpy as np

## Arithmetic Operation

In [4]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [5]:
print(a1,a2)

[1 2 3 4 5] [ 6  7  8  9 10]


In [9]:
# size must be same
sum=a1+a2
sum

array([ 7,  9, 11, 13, 15])

In [10]:
sub=a1-a2
sub

array([-5, -5, -5, -5, -5])

In [11]:
mul=a1*a2
mul

array([ 6, 14, 24, 36, 50])

In [12]:
div=a1/a2
div


array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [13]:
power=a1**a2
power

array([      1,     128,    6561,  262144, 9765625])

## Broadcasting

In [16]:
l=[10,20,30,40]
arr=np.array(l)
arr

array([10, 20, 30, 40])

In [17]:
for i in l:
    print(i+10)

20
30
40
50


In [18]:
arr+10

array([20, 30, 40, 50])

## Deep and Shallow copy

In [20]:
a=np.arange(1,21)

In [21]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
slice=a[:5]
slice

array([1, 2, 3, 4, 5])

In [28]:
slice=slice*10
slice

array([10, 20, 30, 40, 50])

## matrix Operation

In [29]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])

In [31]:
mat1

array([[1, 2],
       [3, 4]])

In [32]:
mat2

array([[5, 6],
       [7, 8]])

In [33]:
mat1+mat2

array([[ 6,  8],
       [10, 12]])

In [35]:
mat1@mat2

array([[19, 22],
       [43, 50]])

In [36]:
mat1.dot(mat2)

array([[19, 22],
       [43, 50]])

In [37]:
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [39]:
mat1.transpose()

array([[1, 3],
       [2, 4]])

# Advance Array Manipulation

## Stacking Array

In [42]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [43]:
a

array([1, 2, 3, 4])

In [44]:
b

array([5, 6, 7, 8])

In [45]:
# vertical stack
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
## Horizontal stack
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## splitting array


In [48]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]