In [2]:
import numpy as np

## Basic Array creation

In [3]:
arr=np.array([1,2,3,4])

In [6]:
arr


array([1, 2, 3, 4])

In [7]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array generation fun

In [10]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [12]:
zeros=np.zeros(6)
zeros

array([0., 0., 0., 0., 0., 0.])

In [13]:
zeros=np.zeros((6,6))
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
ones=np.ones((6,6))
ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
linspace=np.linspace(0,1,100)
linspace

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

## Random Generation Function

In [23]:
random=np.random.rand(5)
random

array([0.42442507, 0.55175063, 0.27792865, 0.88587337, 0.54232357])

In [24]:
np.random.randn(10)

array([ 1.30568447,  1.16719048, -0.26130296, -1.47422783, -0.28004411,
       -0.44249705,  0.54095907, -2.30935279, -0.88931864,  0.32304103])

In [31]:
np.random.randint(10,20,10)

array([17, 15, 11, 10, 16, 17, 17, 16, 15, 15])

## Array Attributes

In [34]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr.shape

(3, 3)

In [38]:
arr.size

9

In [40]:
arr.dtype

dtype('int64')

## Array Methods

In [41]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr.min()

np.int64(1)

In [45]:
arr.max()

np.int64(9)

In [46]:
arr.sum()

np.int64(45)

In [49]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [50]:
arr.mean()

np.float64(5.0)

In [51]:
arr.std()

np.float64(2.581988897471611)

In [52]:
arr.argmax()

np.int64(8)

## Reshaping & Resizing

In [54]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [56]:
arr=arr.reshape(6,5)

In [57]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])