## Numpy Indexing and slicing of vectors

In [7]:
import numpy as np

In [8]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[6]

np.int64(17)

In [4]:
arr[0:5]

array([11, 12, 13, 14, 15])

In [5]:
arr[4:9:3]

array([15, 18])

## Numpy Indexing and slicing of matrix

In [10]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[0]

array([1, 2, 3, 4, 5])

In [14]:
arr[0,0]

np.int64(1)

In [15]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [16]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [17]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

## Boolean Indexing

In [18]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [21]:
bool_index=arr%2==0

In [22]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])